document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("div.sbxztt {");
document.writeln("	border-radius: 4px;");
document.writeln("	box-shadow:0 1px 2px rgba(180,180,180,0.7);");
document.writeln("	    background-color: #fff;");
document.writeln("		zoom: 1;");
document.writeln("		font: 14px/1.5 tahoma,\'//5FAE//8F6F//96C5//9ED1\',\'//5B8B//4F53\',arial,georgia,verdana,helvetica,sans-serif;");
document.writeln("        color: #444;");
document.writeln("}");
document.writeln("tr.firstRowxx {");
document.writeln("	background-color:rgb(139, 69, 19);");
document.writeln("}");
document.writeln(".stylejbx {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("</style>");
document.writeln("<div class=\'sbxztt\'>");

document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("    <table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'100\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' id=\'table2\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\'>");
document.writeln(" <tbody>");
document.writeln("    <tr class=\'firstRowxx\'>");
document.writeln("      <td  height=\'35\'  style=\'background:#FF0000; margin: 0px; border-color: rgb(0, 128, 0); word-break: break-all; text-align: center; font-size: 13pt; line-height: 26px; color: rgb(51, 51, 51); padding-left:2px; padding-right:2px; padding-top:3px; padding-bottom:3px\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-family: 微软雅黑; font-weight: 700; line-height: normal; font-size: 12pt;\'>066期：精解澳门半仙哑谜报，暴富资料就在此</span>");
document.writeln("      </td>");
document.writeln("     </tr>");
document.writeln("   ");
document.writeln("         <tr>");
document.writeln("		<td style=\'margin: 0px; padding: 3px 2px; border-color: rgb(229, 229, 229); word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'color: #000000; font-family: 微软雅黑; text-indent: 2em; font-size: 12pt;\'>必中九肖：牛兔鼠猪马羊狗鸡龙</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中七肖：牛兔鼠猪马羊狗</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中五肖：牛兔鼠猪马</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中三肖：牛兔鼠</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中一肖：牛</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>精选10码：05 29 03 27 18 30 07 43 48 24</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中六码：05 29 03 27 18 30</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中三码：05 29 03</span></p>");
document.writeln("		</td></tr></tbody></table>");
document.writeln("<!--结束end-->");
document.writeln("");

document.writeln("   <!--开始-->");
document.writeln("    <table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'100\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' id=\'table2\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\'>");
document.writeln(" <tbody>");
document.writeln("    <tr class=\'firstRowxx\'>");
document.writeln("      <td  height=\'35\'  style=\'background:#FF0000; margin: 0px; border-color: rgb(0, 128, 0); word-break: break-all; text-align: center; font-size: 13pt; line-height: 26px; color: rgb(51, 51, 51); padding-left:2px; padding-right:2px; padding-top:3px; padding-bottom:3px\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-family: 微软雅黑; font-weight: 700; line-height: normal; font-size: 12pt;\'>065期：精解澳门半仙哑谜报，暴富资料就在此</span>");
document.writeln("      </td>");
document.writeln("     </tr>");
document.writeln("   ");
document.writeln("         <tr>");
document.writeln("		<td style=\'margin: 0px; padding: 3px 2px; border-color: rgb(229, 229, 229); word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'color: #000000; font-family: 微软雅黑; text-indent: 2em; font-size: 12pt;\'>必中九肖：羊<span style=\'background-color: #FFFF00\'>马</span>虎兔鸡鼠龙猪狗</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中七肖：羊<span style=\'background-color: #FFFF00\'>马</span>虎兔鸡鼠龙</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中五肖：羊<span style=\'background-color: #FFFF00\'>马</span>虎兔鸡</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中三肖：羊<span style=\'background-color: #FFFF00\'>马</span>虎</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>精选10码：47 35 <span style=\'background-color: #FFFF00\'>48</span> 24 28 04 03 39 45 33</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中六码：47 35 <span style=\'background-color: #FFFF00\'>48</span> 24 28 04</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中三码：47 35 <span style=\'background-color: #FFFF00\'>48</span></span></p>");
document.writeln("		</td></tr></tbody></table>");
document.writeln("<!--结束end-->");
document.writeln("");

document.writeln("   <!--开始-->");
document.writeln("    <table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'100\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' id=\'table2\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\'>");
document.writeln(" <tbody>");
document.writeln("    <tr class=\'firstRowxx\'>");
document.writeln("      <td  height=\'35\'  style=\'background:#FF0000; margin: 0px; border-color: rgb(0, 128, 0); word-break: break-all; text-align: center; font-size: 13pt; line-height: 26px; color: rgb(51, 51, 51); padding-left:2px; padding-right:2px; padding-top:3px; padding-bottom:3px\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-family: 微软雅黑; font-weight: 700; line-height: normal; font-size: 12pt;\'>063期：精解澳门半仙哑谜报，暴富资料就在此</span>");
document.writeln("      </td>");
document.writeln("     </tr>");
document.writeln("   ");
document.writeln("         <tr>");
document.writeln("		<td style=\'margin: 0px; padding: 3px 2px; border-color: rgb(229, 229, 229); word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'color: #000000; font-family: 微软雅黑; text-indent: 2em; font-size: 12pt;\'>必中九肖：鼠猴蛇马<span style=\'background-color: #FFFF00\'>羊</span>虎狗兔猪</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中七肖：鼠猴蛇马<span style=\'background-color: #FFFF00\'>羊</span>虎狗</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中五肖：鼠猴蛇马<span style=\'background-color: #FFFF00\'>羊</span></span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>精选10码：06 42 22 10 25 49 12 48 47 <span style=\'background-color: #FFFF00\'>23</span></span></p>");
document.writeln("		</td></tr></tbody></table>");
document.writeln("<!--结束end-->");

document.writeln("   <!--开始-->");
document.writeln("    <table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'100\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' id=\'table2\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\'>");
document.writeln(" <tbody>");
document.writeln("    <tr class=\'firstRowxx\'>");
document.writeln("      <td  height=\'35\'  style=\'background:#FF0000; margin: 0px; border-color: rgb(0, 128, 0); word-break: break-all; text-align: center; font-size: 13pt; line-height: 26px; color: rgb(51, 51, 51); padding-left:2px; padding-right:2px; padding-top:3px; padding-bottom:3px\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-family: 微软雅黑; font-weight: 700; line-height: normal; font-size: 12pt;\'>062期：精解澳门半仙哑谜报，暴富资料就在此</span>");
document.writeln("      </td>");
document.writeln("     </tr>");
document.writeln("   ");
document.writeln("         <tr>");
document.writeln("		<td style=\'margin: 0px; padding: 3px 2px; border-color: rgb(229, 229, 229); word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'color: #000000; font-family: 微软雅黑; text-indent: 2em; font-size: 12pt;\'>必中九肖：鸡鼠猪蛇兔<span style=\'background-color: #FFFF00\'>羊</span>龙马虎</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中七肖：鸡鼠猪蛇兔<span style=\'background-color: #FFFF00\'>羊</span>龙</span></p>");
document.writeln("		</td></tr></tbody></table>");
document.writeln("<!--结束end-->");
document.writeln("");

document.writeln("   <!--开始-->");
document.writeln("    <table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'100\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' id=\'table2\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\'>");
document.writeln(" <tbody>");
document.writeln("    <tr class=\'firstRowxx\'>");
document.writeln("      <td  height=\'35\'  style=\'background:#FF0000; margin: 0px; border-color: rgb(0, 128, 0); word-break: break-all; text-align: center; font-size: 13pt; line-height: 26px; color: rgb(51, 51, 51); padding-left:2px; padding-right:2px; padding-top:3px; padding-bottom:3px\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-family: 微软雅黑; font-weight: 700; line-height: normal; font-size: 12pt;\'>061期：精解澳门半仙哑谜报，暴富资料就在此</span>");
document.writeln("      </td>");
document.writeln("     </tr>");
document.writeln("   ");
document.writeln("         <tr>");
document.writeln("		<td style=\'margin: 0px; padding: 3px 2px; border-color: rgb(229, 229, 229); word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'color: #000000; font-family: 微软雅黑; text-indent: 2em; font-size: 12pt;\'>必中九肖：鸡鼠羊龙虎狗牛兔<span style=\'background-color: #FFFF00\'>猴</span></span></p>");
document.writeln("		</td></tr></tbody></table>");
document.writeln("<!--结束end-->");
document.writeln("");
document.writeln("");

document.writeln("   <!--开始-->");
document.writeln("    <table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'100\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' id=\'table2\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\'>");
document.writeln(" <tbody>");
document.writeln("    <tr class=\'firstRowxx\'>");
document.writeln("      <td  height=\'35\'  style=\'background:#FF0000; margin: 0px; border-color: rgb(0, 128, 0); word-break: break-all; text-align: center; font-size: 13pt; line-height: 26px; color: rgb(51, 51, 51); padding-left:2px; padding-right:2px; padding-top:3px; padding-bottom:3px\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-family: 微软雅黑; font-weight: 700; line-height: normal; font-size: 12pt;\'>060期：精解澳门半仙哑谜报，暴富资料就在此</span>");
document.writeln("      </td>");
document.writeln("     </tr>");
document.writeln("   ");
document.writeln("         <tr>");
document.writeln("		<td style=\'margin: 0px; padding: 3px 2px; border-color: rgb(229, 229, 229); word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'color: #000000; font-family: 微软雅黑; text-indent: 2em; font-size: 12pt;\'>必中九肖：蛇牛狗马<span style=\'background-color: #FFFF00\'>羊</span>鸡龙鼠猪</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中七肖：蛇牛狗马<span style=\'background-color: #FFFF00\'>羊</span>鸡龙</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中五肖：蛇牛狗马<span style=\'background-color: #FFFF00\'>羊</span></span></p>");
document.writeln("		</td></tr></tbody></table>");
document.writeln("<!--结束end-->");
document.writeln("");
document.writeln("");
