document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("div.sbxztt {");
document.writeln("	border-radius: 4px;");
document.writeln("	box-shadow:0 1px 2px rgba(180,180,180,0.7);");
document.writeln("	    background-color: #fff;");
document.writeln("		zoom: 1;");
document.writeln("		font: 14px/1.5 tahoma,\'//5FAE//8F6F//96C5//9ED1\',\'//5B8B//4F53\',arial,georgia,verdana,helvetica,sans-serif;");
document.writeln("        color: #444;");
document.writeln("}");
document.writeln("tr.firstRowxx {");
document.writeln("	background-color:rgb(139, 69, 19);");
document.writeln("}");
document.writeln(".stylejbx {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("</style>");
document.writeln("<div class=\'sbxztt\'>");

document.writeln("   <!--开始-->");
document.writeln("    <table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'100\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' id=\'table2\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\'>");
document.writeln(" <tbody>");
document.writeln("    <tr class=\'firstRowxx\'>");
document.writeln("      <td  height=\'35\'  style=\'background:#FF0000; margin: 0px; border-color: rgb(0, 128, 0); word-break: break-all; text-align: center; font-size: 13pt; line-height: 26px; color: rgb(51, 51, 51); padding-left:2px; padding-right:2px; padding-top:3px; padding-bottom:3px\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-family: 微软雅黑; font-weight: 700; line-height: normal; font-size: 12pt;\'>066期：六肖三码，王中王885560.com</span>");
document.writeln("      </td>");
document.writeln("     </tr>");
document.writeln("   ");
document.writeln("         <tr>");
document.writeln("		<td style=\'margin: 0px; padding: 3px 2px; border-color: rgb(229, 229, 229); word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中六肖：猪狗猴羊鼠虎</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中三肖：猪狗猴</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中一肖：猪</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>精选12码：07.43.08.32.22.34.35.47.06.18.28.04</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中六码：07.43.08.32.22.34</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中一码：07</span></p>");
document.writeln("		</td></tr></tbody></table>");
document.writeln("<!--结束end-->");
document.writeln("");
document.writeln("");

document.writeln("   <!--开始-->");
document.writeln("    <table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'100\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' id=\'table2\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\'>");
document.writeln(" <tbody>");
document.writeln("    <tr class=\'firstRowxx\'>");
document.writeln("      <td  height=\'35\'  style=\'background:#FF0000; margin: 0px; border-color: rgb(0, 128, 0); word-break: break-all; text-align: center; font-size: 13pt; line-height: 26px; color: rgb(51, 51, 51); padding-left:2px; padding-right:2px; padding-top:3px; padding-bottom:3px\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-family: 微软雅黑; font-weight: 700; line-height: normal; font-size: 12pt;\'>065期：六肖三码，王中王885560.com</span>");
document.writeln("      </td>");
document.writeln("     </tr>");
document.writeln("   ");
document.writeln("         <tr>");
document.writeln("		<td style=\'margin: 0px; padding: 3px 2px; border-color: rgb(229, 229, 229); word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中六肖：狗羊兔猴蛇<span style=\'background-color: #FFFF00\'>马</span></span></p>");
document.writeln("		</td></tr></tbody></table>");
document.writeln("<!--结束end-->");
document.writeln("");

document.writeln("   <!--开始-->");
document.writeln("    <table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'100\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' id=\'table2\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\'>");
document.writeln(" <tbody>");
document.writeln("    <tr class=\'firstRowxx\'>");
document.writeln("      <td  height=\'35\'  style=\'background:#FF0000; margin: 0px; border-color: rgb(0, 128, 0); word-break: break-all; text-align: center; font-size: 13pt; line-height: 26px; color: rgb(51, 51, 51); padding-left:2px; padding-right:2px; padding-top:3px; padding-bottom:3px\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-family: 微软雅黑; font-weight: 700; line-height: normal; font-size: 12pt;\'>064期：六肖三码，王中王885560.com</span>");
document.writeln("      </td>");
document.writeln("     </tr>");
document.writeln("   ");
document.writeln("         <tr>");
document.writeln("		<td style=\'margin: 0px; padding: 3px 2px; border-color: rgb(229, 229, 229); word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中六肖：牛马鸡鼠虎<span style=\'background-color: #FFFF00\'>猪</span></span></p>");
document.writeln("		</td></tr></tbody></table>");
document.writeln("<!--结束end-->");
document.writeln("");

document.writeln("   <!--开始-->");
document.writeln("    <table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'100\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' id=\'table2\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\'>");
document.writeln(" <tbody>");
document.writeln("    <tr class=\'firstRowxx\'>");
document.writeln("      <td  height=\'35\'  style=\'background:#FF0000; margin: 0px; border-color: rgb(0, 128, 0); word-break: break-all; text-align: center; font-size: 13pt; line-height: 26px; color: rgb(51, 51, 51); padding-left:2px; padding-right:2px; padding-top:3px; padding-bottom:3px\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-family: 微软雅黑; font-weight: 700; line-height: normal; font-size: 12pt;\'>063期：六肖三码，王中王885560.com</span>");
document.writeln("      </td>");
document.writeln("     </tr>");
document.writeln("   ");
document.writeln("         <tr>");
document.writeln("		<td style=\'margin: 0px; padding: 3px 2px; border-color: rgb(229, 229, 229); word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中六肖：兔<span style=\'background-color: #FFFF00\'>羊</span>牛马猪龙</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中三肖：兔<span style=\'background-color: #FFFF00\'>羊</span>牛</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>精选12码：27.15.47.<span style=\'background-color: #FFFF00\'>23</span>.17.29.48.24.43.31.02.26</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中六码：27.15.47.<span style=\'background-color: #FFFF00\'>23</span>.17.29</span></p>");
document.writeln("		</td></tr></tbody></table>");
document.writeln("<!--结束end-->");
document.writeln("");
document.writeln("");

document.writeln("   <!--开始-->");
document.writeln("    <table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'100\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' id=\'table2\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\'>");
document.writeln(" <tbody>");
document.writeln("    <tr class=\'firstRowxx\'>");
document.writeln("      <td  height=\'35\'  style=\'background:#FF0000; margin: 0px; border-color: rgb(0, 128, 0); word-break: break-all; text-align: center; font-size: 13pt; line-height: 26px; color: rgb(51, 51, 51); padding-left:2px; padding-right:2px; padding-top:3px; padding-bottom:3px\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-family: 微软雅黑; font-weight: 700; line-height: normal; font-size: 12pt;\'>062期：六肖三码，王中王885560.com</span>");
document.writeln("      </td>");
document.writeln("     </tr>");
document.writeln("   ");
document.writeln("         <tr>");
document.writeln("		<td style=\'margin: 0px; padding: 3px 2px; border-color: rgb(229, 229, 229); word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中六肖：<span style=\'background-color: #FFFF00\'>羊</span>马虎兔鸡鼠</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中三肖：<span style=\'background-color: #FFFF00\'>羊</span>马虎</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中一肖：<span style=\'background-color: #FFFF00\'>羊</span></span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>精选12码：47.<span style=\'background-color: #FFFF00\'>35</span>.48.24.28.04.03.39.45.33.42.18</span></p>");
document.writeln("		<p style=\'font-size: 13pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("		<span style=\'text-indent: 28px; color: #000000; font-family: 微软雅黑; font-size: 12pt;\'>必中六码：47.<span style=\'background-color: #FFFF00\'>35</span>.48.24.28.04</span></p>");
document.writeln("		</td></tr></tbody></table>");
document.writeln("<!--结束end-->");
document.writeln("");
