document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>醉八仙622727.com</title>");
document.writeln("<style>");
document.writeln("	#jiuxiao td {border-bottom: 3px solid blue;font-size:14px;}");
document.writeln("");
document.writeln("	body,td,th {");
document.writeln("	font-family: tahoma, //5FAE//8F6F//96C5//9ED1, //5B8B//4F53, arial, georgia, verdana, helvetica, sans-serif;");
document.writeln("}");
document.writeln(".pic-list { padding-top: 10px; text-align: center;}");
document.writeln(".pic-list span { float: left; width: 50%;}");
document.writeln(".pic-list span img { width: 90%; height: 250px; margin: 0 auto;}");
document.writeln(".pic-list span em { height: 40px; line-height: 40px;}");
document.writeln("");
document.writeln("@media screen and (max-width:500px){  ");
document.writeln(".pic-list span img { height: 200px;}");
document.writeln(" } ");
document.writeln("");
document.writeln("@media screen and (max-width:450px){  ");
document.writeln(".pic-list span img { height: 150px;}");
document.writeln(" } ");
document.writeln("");
document.writeln("@media screen and (max-width:400px){  ");
document.writeln(".pic-list span img { height: 130px;}");
document.writeln(" }");
document.writeln("/*图片放大*/");
document.writeln(".photoBox{display:inline-block;position:relative;}");
document.writeln(".photoBox img{display:block;}");
document.writeln(".zoom{}");
document.writeln(".photoArea{zoom:1;}");
document.writeln(".minifier{}");
document.writeln(".photoArea {}");
document.writeln(".photoArea img { width: 99%; height: auto;}");
document.writeln("");
document.writeln(".clearfix:after {content: \'.\';display: block;height: 0;clear: both;overflow: hidden;visibility: hidden }");
document.writeln(".clearfix {");
document.writeln("*zoom:1 }");
document.writeln("");
document.writeln(".kj-link-tit { height: 40px; line-height: 40px; text-align: center; font-size: 16px; color: #0063ca; border-bottom: solid 3px #0063ca; background: #eee; background-image: linear-gradient(to top, #f7f7f7,#fff);}");
document.writeln(".kj-link-box { padding: 5px 10px; text-align: center;}");
document.writeln(".kj-link-box ul {}");
document.writeln(".kj-link-box ul li {float: left; width: 33.33%; padding-right: 3%;}");
document.writeln(".kj-link-box ul li:nth-child(3n) { padding-right: 0;}");
document.writeln(".kj-link-box ul li a { width: 100%; height: 30px; line-height: 30px; margin: 5px 0; border: solid 1px #ddd; box-shadow: 0 2px 5px rgba(0,0,0,0.1); border-radius: 6px; display: inline-block; background-image: linear-gradient(to top, #f7f7f7,#fff);}");
document.writeln("");
document.writeln(".md-links { padding-top: 10px; text-align: center;}");
document.writeln(".md-links ul { *zoom:1 }");
document.writeln(".md-links ul:after {content: \'.\';display: block;height: 0;clear: both;overflow: hidden;visibility: hidden }");
document.writeln(".md-links ul li { float: left; width: 25%; padding-bottom: 10px;}");
document.writeln(".md-links ul li img { width: 45px; height: 45px; margin-bottom: 5px;}");
document.writeln(".md-links ul li p {");
document.writeln("	overflow: hidden;");
document.writeln("	white-space: nowrap;");
document.writeln("	text-overflow: ellipsis;");
document.writeln("	color: #F00;");
document.writeln("	font-size: 13px;");
document.writeln("}");
document.writeln("");
document.writeln(".clearfix:after {content: \'.\';display: block;height: 0;clear: both;overflow: hidden;visibility: hidden;}");
document.writeln(".clearfix {*zoom:1 }");
document.writeln("");
document.writeln(".cgi-tuijian {}");
document.writeln(".cgi-tj-l { float: left; width: 18%; margin-right: 2%; padding-top: 10px;}");
document.writeln(".cgi-tj-l img { width: 100%; height: 100px;}");
document.writeln(".cgi-tj-r { float: right; width: 80%;}");
document.writeln(".cgi-tj-r ul {}");
document.writeln(".cgi-tj-r ul li { height: 40px; line-height: 40px; border-bottom: solid 1px #ddd; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;}");
document.writeln(".cgi-tj-r ul li:last-child { border-bottom: 0;}");
document.writeln(".cgi-tj-r ul li a {}");
document.writeln("");
document.writeln("@media screen and (max-width:640px){  ");
document.writeln(".cgi-tj-l { width: 32%; margin-right: 3%;}");
document.writeln(".cgi-tj-r { width: 65%;}");
document.writeln(" }");
document.writeln("@media screen and (max-width:550px){  ");
document.writeln(".cgi-tj-l { width: 32%; margin-right: 3%;}");
document.writeln(".cgi-tj-r { width: 65%;}");
document.writeln(" }");
document.writeln("@media screen and (max-width:450px){  ");
document.writeln(".cgi-tj-l { width: 32%; margin-right: 3%;}");
document.writeln(".cgi-tj-r { width: 65%;}");
document.writeln(" }");
document.writeln("");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("<!--图片推荐start-->");
document.writeln("<div class=\'box\'>");
document.writeln("<div class=\'pic-list grey-line clearfix\'>");
document.writeln("");
document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/m41.jpg\' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>美女六肖</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");
document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/382.jpg\' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>美女六肖图</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");
document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/b14.jpg\' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>另美女六肖</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");
document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/d25.jpg\' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>美女六肖中特</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");

document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/d26.jpg\' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>美女七肖</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");
document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/114109.jpg\' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>美女九肖</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");
document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/114111.jpg\' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>美女九肖图</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");
document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/114110.jpg\' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>美女报码</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");


document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/114112.jpg\' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>美女报码图</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");
document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/11428.jpg' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>美女劲爆图</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");

document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/d17.jpg\' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>美女五行图</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");
document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/mntmb.jpg' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>美女特码报</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");

document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/61.jpg\' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>美女报</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");
document.writeln("    <span class=\'photoBox\'><img src=\'https://amo.phseo1.com:4949/col/66/v7.jpg' class=\'zoom\' onClick=\'zoom_image($(this).parent());\'/><em>环球美女报</em></span>");
document.writeln("    <div class=\'photoArea\' style=\'display:none;\'><p><img src=\'about:blank\' class=\'minifier\' onClick=\'zoom_image($(this).parent().parent());\'></p></div>");
document.writeln("    ");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<!--图片推荐end-->");
document.writeln("");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");