document.writeln("<meta charset=\'utf-8\'>");
document.writeln("");
document.writeln("<style>");
document.writeln(".bizhong123 { width:100%; margin:0 auto;}");
document.writeln(".bizhong123-box{ float: left; width: 100%; display:none;}");
document.writeln(".action-bz{display:block;}");
document.writeln(".bizhong123-page { height: 40px; padding-top: 5px;}");
document.writeln(".bizhong123-btn { float: left; width: calc( 50% - 10px); height: 38px; line-height: 38px; margin-right: 10px; text-align: center; display: inline-block; background: #aaa; border: solid 1px #ccc; border-radius: 5px; background-image: linear-gradient(to top, #ddd, #fff); cursor: pointer;}");
document.writeln(".bizhong123-btn:hover { background-image: linear-gradient(to bottom, #ddd, #fff);}");
document.writeln(".bizhong123-btn.bizhong123-pre {}");
document.writeln(".bizhong123-btn.bizhong123-next { margin-right: 0;}");
document.writeln("");
document.writeln(".bizhong123 img {width:100%; border-collapse: collapse; font-weight: bold;}");
document.writeln("</style>");
document.writeln("    ");
document.writeln("<div class=\'bizhong123-page\'>");
document.writeln("    <span class=\'bizhong123-btn bizhong123-pre\' onclick=\'prex();\'>下一期</span> ");
document.writeln("    <span class=\'bizhong123-btn bizhong123-next\' onclick=\'nextx();\'>上一期</span>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("\'https://amo.phseo1.com:4949/col/66/098.jpg\', "); 
document.writeln("\'https://amo.phseo1.com:4949/col/65/098.jpg\', "); 
document.writeln("\'https://amo.phseo1.com:4949/col/64/098.jpg\', "); 
document.writeln("\'https://amo.phseo1.com:4949/col/63/098.jpg\', "); 
document.writeln("\'https://amo.phseo1.com:4949/col/62/098.jpg\', "); 
document.writeln("\'https://amo.phseo1.com:4949/col/61/098.jpg\', "); 
document.writeln("\'https://amo.phseo1.com:4949/col/60/098.jpg\', "); 
document.writeln("\'https://amo.phseo1.com:4949/col/59/098.jpg\', "); 
document.writeln("\'https://amo.phseo1.com:4949/col/58/098.jpg\', "); 
document.writeln("\'https://amo.phseo1.com:4949/col/57/098.jpg\', "); 
document.writeln("\'https://amo.phseo1.com:4949/col/56/098.jpg\', "); 
document.writeln("\'https://amo.phseo1.com:4949/col/55/098.jpg\', "); 
document.writeln("");
document.writeln("");
document.writeln(");");
document.writeln("    var indexx=0;");
document.writeln("    function nextx(){");
document.writeln("        indexx++;");
document.writeln("        if(indexx==picArrx.length){");
document.writeln("            indexx=0;");
document.writeln("        }");
document.writeln("        document.getElementById(\'123sjkjpicx\').src=picArrx[indexx];");
document.writeln("    }");
document.writeln("    function prex(){");
document.writeln("        indexx--;");
document.writeln("        if(indexx<0){");
document.writeln("            indexx=picArrx.length-1;");
document.writeln("        }");
document.writeln("        document.getElementById(\'123sjkjpicx\').src=picArrx[indexx];");
document.writeln("    }");
document.writeln("</script>");
